// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/api.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Interval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interval) Reset() {
	*x = Interval{}
	mi := &file_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interval) ProtoMessage() {}

func (x *Interval) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interval.ProtoReflect.Descriptor instead.
func (*Interval) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *Interval) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Interval) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// the name is an index for the lookup table of event names
	Name        uint32 `protobuf:"varint,2,opt,name=name,proto3" json:"name,omitempty"`
	Location    string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// each element is an index for the lookup table of tag names
	Tags     []uint32             `protobuf:"varint,5,rep,packed,name=tags,proto3" json:"tags,omitempty"`
	Interval *Interval            `protobuf:"bytes,6,opt,name=interval,proto3" json:"interval,omitempty"`
	Duration *durationpb.Duration `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	// Types that are valid to be assigned to Trigger:
	//
	//	*Event_Relative
	//	*Event_Absolute
	//	*Event_None
	Trigger       isEvent_Trigger `protobuf_oneof:"trigger"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetName() uint32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *Event) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetTags() []uint32 {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Event) GetInterval() *Interval {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *Event) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Event) GetTrigger() isEvent_Trigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *Event) GetRelative() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Trigger.(*Event_Relative); ok {
			return x.Relative
		}
	}
	return nil
}

func (x *Event) GetAbsolute() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Trigger.(*Event_Absolute); ok {
			return x.Absolute
		}
	}
	return nil
}

func (x *Event) GetNone() bool {
	if x != nil {
		if x, ok := x.Trigger.(*Event_None); ok {
			return x.None
		}
	}
	return false
}

type isEvent_Trigger interface {
	isEvent_Trigger()
}

type Event_Relative struct {
	Relative *durationpb.Duration `protobuf:"bytes,8,opt,name=relative,proto3,oneof"`
}

type Event_Absolute struct {
	Absolute *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=absolute,proto3,oneof"`
}

type Event_None struct {
	None bool `protobuf:"varint,10,opt,name=none,proto3,oneof"`
}

func (*Event_Relative) isEvent_Trigger() {}

func (*Event_Absolute) isEvent_Trigger() {}

func (*Event_None) isEvent_Trigger() {}

// Calendar
type CalendarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalendarRequest) Reset() {
	*x = CalendarRequest{}
	mi := &file_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarRequest) ProtoMessage() {}

func (x *CalendarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarRequest.ProtoReflect.Descriptor instead.
func (*CalendarRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{2}
}

type CalendarResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Sources       []*CalendarResponse_Source `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalendarResponse) Reset() {
	*x = CalendarResponse{}
	mi := &file_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarResponse) ProtoMessage() {}

func (x *CalendarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarResponse.ProtoReflect.Descriptor instead.
func (*CalendarResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *CalendarResponse) GetSources() []*CalendarResponse_Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

// Events
type EventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      *Interval              `protobuf:"bytes,1,opt,name=interval,proto3" json:"interval,omitempty"`
	Timezone      string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	mi := &file_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *EventsRequest) GetInterval() *Interval {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *EventsRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type EventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventNames    []string               `protobuf:"bytes,1,rep,name=event_names,json=eventNames,proto3" json:"event_names,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Events        []*Event               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsResponse) Reset() {
	*x = EventsResponse{}
	mi := &file_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse) ProtoMessage() {}

func (x *EventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse.ProtoReflect.Descriptor instead.
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *EventsResponse) GetEventNames() []string {
	if x != nil {
		return x.EventNames
	}
	return nil
}

func (x *EventsResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// UpdateEvents
type UpdateEventsRequest struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Updated       []*UpdateEventsRequest_UpdatedEvent `protobuf:"bytes,1,rep,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventsRequest) Reset() {
	*x = UpdateEventsRequest{}
	mi := &file_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventsRequest) ProtoMessage() {}

func (x *UpdateEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventsRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventsRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEventsRequest) GetUpdated() []*UpdateEventsRequest_UpdatedEvent {
	if x != nil {
		return x.Updated
	}
	return nil
}

type UpdateEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventsResponse) Reset() {
	*x = UpdateEventsResponse{}
	mi := &file_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventsResponse) ProtoMessage() {}

func (x *UpdateEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventsResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventsResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{7}
}

type CalendarResponse_Source struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CalendarServer string                 `protobuf:"bytes,1,opt,name=calendar_server,json=calendarServer,proto3" json:"calendar_server,omitempty"`
	Names          []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CalendarResponse_Source) Reset() {
	*x = CalendarResponse_Source{}
	mi := &file_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarResponse_Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarResponse_Source) ProtoMessage() {}

func (x *CalendarResponse_Source) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarResponse_Source.ProtoReflect.Descriptor instead.
func (*CalendarResponse_Source) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CalendarResponse_Source) GetCalendarServer() string {
	if x != nil {
		return x.CalendarServer
	}
	return ""
}

func (x *CalendarResponse_Source) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type UpdateEventsRequest_UpdatedEvent struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Id            uint32                                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                                   `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Location      *string                                   `protobuf:"bytes,3,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Description   *string                                   `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Tags          *UpdateEventsRequest_UpdatedEvent_Tags    `protobuf:"bytes,5,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	Interval      *Interval                                 `protobuf:"bytes,6,opt,name=interval,proto3,oneof" json:"interval,omitempty"`
	Trigger       *UpdateEventsRequest_UpdatedEvent_Trigger `protobuf:"bytes,7,opt,name=trigger,proto3,oneof" json:"trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventsRequest_UpdatedEvent) Reset() {
	*x = UpdateEventsRequest_UpdatedEvent{}
	mi := &file_v1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventsRequest_UpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventsRequest_UpdatedEvent) ProtoMessage() {}

func (x *UpdateEventsRequest_UpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventsRequest_UpdatedEvent.ProtoReflect.Descriptor instead.
func (*UpdateEventsRequest_UpdatedEvent) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{6, 0}
}

func (x *UpdateEventsRequest_UpdatedEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEventsRequest_UpdatedEvent) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateEventsRequest_UpdatedEvent) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *UpdateEventsRequest_UpdatedEvent) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateEventsRequest_UpdatedEvent) GetTags() *UpdateEventsRequest_UpdatedEvent_Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateEventsRequest_UpdatedEvent) GetInterval() *Interval {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *UpdateEventsRequest_UpdatedEvent) GetTrigger() *UpdateEventsRequest_UpdatedEvent_Trigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

type UpdateEventsRequest_UpdatedEvent_Tags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventsRequest_UpdatedEvent_Tags) Reset() {
	*x = UpdateEventsRequest_UpdatedEvent_Tags{}
	mi := &file_v1_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventsRequest_UpdatedEvent_Tags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventsRequest_UpdatedEvent_Tags) ProtoMessage() {}

func (x *UpdateEventsRequest_UpdatedEvent_Tags) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventsRequest_UpdatedEvent_Tags.ProtoReflect.Descriptor instead.
func (*UpdateEventsRequest_UpdatedEvent_Tags) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{6, 0, 0}
}

func (x *UpdateEventsRequest_UpdatedEvent_Tags) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type UpdateEventsRequest_UpdatedEvent_Trigger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Trigger:
	//
	//	*UpdateEventsRequest_UpdatedEvent_Trigger_Relative
	//	*UpdateEventsRequest_UpdatedEvent_Trigger_Absolute
	//	*UpdateEventsRequest_UpdatedEvent_Trigger_None
	Trigger       isUpdateEventsRequest_UpdatedEvent_Trigger_Trigger `protobuf_oneof:"trigger"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventsRequest_UpdatedEvent_Trigger) Reset() {
	*x = UpdateEventsRequest_UpdatedEvent_Trigger{}
	mi := &file_v1_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventsRequest_UpdatedEvent_Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventsRequest_UpdatedEvent_Trigger) ProtoMessage() {}

func (x *UpdateEventsRequest_UpdatedEvent_Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventsRequest_UpdatedEvent_Trigger.ProtoReflect.Descriptor instead.
func (*UpdateEventsRequest_UpdatedEvent_Trigger) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{6, 0, 1}
}

func (x *UpdateEventsRequest_UpdatedEvent_Trigger) GetTrigger() isUpdateEventsRequest_UpdatedEvent_Trigger_Trigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *UpdateEventsRequest_UpdatedEvent_Trigger) GetRelative() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Trigger.(*UpdateEventsRequest_UpdatedEvent_Trigger_Relative); ok {
			return x.Relative
		}
	}
	return nil
}

func (x *UpdateEventsRequest_UpdatedEvent_Trigger) GetAbsolute() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Trigger.(*UpdateEventsRequest_UpdatedEvent_Trigger_Absolute); ok {
			return x.Absolute
		}
	}
	return nil
}

func (x *UpdateEventsRequest_UpdatedEvent_Trigger) GetNone() bool {
	if x != nil {
		if x, ok := x.Trigger.(*UpdateEventsRequest_UpdatedEvent_Trigger_None); ok {
			return x.None
		}
	}
	return false
}

type isUpdateEventsRequest_UpdatedEvent_Trigger_Trigger interface {
	isUpdateEventsRequest_UpdatedEvent_Trigger_Trigger()
}

type UpdateEventsRequest_UpdatedEvent_Trigger_Relative struct {
	Relative *durationpb.Duration `protobuf:"bytes,1,opt,name=relative,proto3,oneof"`
}

type UpdateEventsRequest_UpdatedEvent_Trigger_Absolute struct {
	Absolute *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=absolute,proto3,oneof"`
}

type UpdateEventsRequest_UpdatedEvent_Trigger_None struct {
	None bool `protobuf:"varint,3,opt,name=none,proto3,oneof"`
}

func (*UpdateEventsRequest_UpdatedEvent_Trigger_Relative) isUpdateEventsRequest_UpdatedEvent_Trigger_Trigger() {
}

func (*UpdateEventsRequest_UpdatedEvent_Trigger_Absolute) isUpdateEventsRequest_UpdatedEvent_Trigger_Trigger() {
}

func (*UpdateEventsRequest_UpdatedEvent_Trigger_None) isUpdateEventsRequest_UpdatedEvent_Trigger_Trigger() {
}

var File_v1_api_proto protoreflect.FileDescriptor

const file_v1_api_proto_rawDesc = "" +
	"\n" +
	"\fv1/api.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"j\n" +
	"\bInterval\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xef\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\rR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\rR\x04tags\x12%\n" +
	"\binterval\x18\x06 \x01(\v2\t.IntervalR\binterval\x125\n" +
	"\bduration\x18\a \x01(\v2\x19.google.protobuf.DurationR\bduration\x127\n" +
	"\brelative\x18\b \x01(\v2\x19.google.protobuf.DurationH\x00R\brelative\x128\n" +
	"\babsolute\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\babsolute\x12\x14\n" +
	"\x04none\x18\n" +
	" \x01(\bH\x00R\x04noneB\t\n" +
	"\atrigger\"\x11\n" +
	"\x0fCalendarRequest\"\x8f\x01\n" +
	"\x10CalendarResponse\x122\n" +
	"\asources\x18\x01 \x03(\v2\x18.CalendarResponse.SourceR\asources\x1aG\n" +
	"\x06Source\x12'\n" +
	"\x0fcalendar_server\x18\x01 \x01(\tR\x0ecalendarServer\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\"R\n" +
	"\rEventsRequest\x12%\n" +
	"\binterval\x18\x01 \x01(\v2\t.IntervalR\binterval\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\"e\n" +
	"\x0eEventsResponse\x12\x1f\n" +
	"\vevent_names\x18\x01 \x03(\tR\n" +
	"eventNames\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x1e\n" +
	"\x06events\x18\x03 \x03(\v2\x06.EventR\x06events\"\x93\x05\n" +
	"\x13UpdateEventsRequest\x12;\n" +
	"\aupdated\x18\x01 \x03(\v2!.UpdateEventsRequest.UpdatedEventR\aupdated\x1a\xbe\x04\n" +
	"\fUpdatedEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\blocation\x18\x03 \x01(\tH\x01R\blocation\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01\x12?\n" +
	"\x04tags\x18\x05 \x01(\v2&.UpdateEventsRequest.UpdatedEvent.TagsH\x03R\x04tags\x88\x01\x01\x12*\n" +
	"\binterval\x18\x06 \x01(\v2\t.IntervalH\x04R\binterval\x88\x01\x01\x12H\n" +
	"\atrigger\x18\a \x01(\v2).UpdateEventsRequest.UpdatedEvent.TriggerH\x05R\atrigger\x88\x01\x01\x1a\x1e\n" +
	"\x04Tags\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\x1a\x9d\x01\n" +
	"\aTrigger\x127\n" +
	"\brelative\x18\x01 \x01(\v2\x19.google.protobuf.DurationH\x00R\brelative\x128\n" +
	"\babsolute\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\babsolute\x12\x14\n" +
	"\x04none\x18\x03 \x01(\bH\x00R\x04noneB\t\n" +
	"\atriggerB\a\n" +
	"\x05_nameB\v\n" +
	"\t_locationB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_tagsB\v\n" +
	"\t_intervalB\n" +
	"\n" +
	"\b_trigger\"\x16\n" +
	"\x14UpdateEventsResponse2\xaa\x01\n" +
	"\x0fCalendarService\x12/\n" +
	"\bCalendar\x12\x10.CalendarRequest\x1a\x11.CalendarResponse\x12)\n" +
	"\x06Events\x12\x0e.EventsRequest\x1a\x0f.EventsResponse\x12;\n" +
	"\fUpdateEvents\x12\x14.UpdateEventsRequest\x1a\x15.UpdateEventsResponseB\x1cB\bApiProtoP\x01Z\x0ecalutil/api/v1b\x06proto3"

var (
	file_v1_api_proto_rawDescOnce sync.Once
	file_v1_api_proto_rawDescData []byte
)

func file_v1_api_proto_rawDescGZIP() []byte {
	file_v1_api_proto_rawDescOnce.Do(func() {
		file_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_api_proto_rawDesc), len(file_v1_api_proto_rawDesc)))
	})
	return file_v1_api_proto_rawDescData
}

var file_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_v1_api_proto_goTypes = []any{
	(*Interval)(nil),                                 // 0: Interval
	(*Event)(nil),                                    // 1: Event
	(*CalendarRequest)(nil),                          // 2: CalendarRequest
	(*CalendarResponse)(nil),                         // 3: CalendarResponse
	(*EventsRequest)(nil),                            // 4: EventsRequest
	(*EventsResponse)(nil),                           // 5: EventsResponse
	(*UpdateEventsRequest)(nil),                      // 6: UpdateEventsRequest
	(*UpdateEventsResponse)(nil),                     // 7: UpdateEventsResponse
	(*CalendarResponse_Source)(nil),                  // 8: CalendarResponse.Source
	(*UpdateEventsRequest_UpdatedEvent)(nil),         // 9: UpdateEventsRequest.UpdatedEvent
	(*UpdateEventsRequest_UpdatedEvent_Tags)(nil),    // 10: UpdateEventsRequest.UpdatedEvent.Tags
	(*UpdateEventsRequest_UpdatedEvent_Trigger)(nil), // 11: UpdateEventsRequest.UpdatedEvent.Trigger
	(*timestamppb.Timestamp)(nil),                    // 12: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),                      // 13: google.protobuf.Duration
}
var file_v1_api_proto_depIdxs = []int32{
	12, // 0: Interval.start:type_name -> google.protobuf.Timestamp
	12, // 1: Interval.end:type_name -> google.protobuf.Timestamp
	0,  // 2: Event.interval:type_name -> Interval
	13, // 3: Event.duration:type_name -> google.protobuf.Duration
	13, // 4: Event.relative:type_name -> google.protobuf.Duration
	12, // 5: Event.absolute:type_name -> google.protobuf.Timestamp
	8,  // 6: CalendarResponse.sources:type_name -> CalendarResponse.Source
	0,  // 7: EventsRequest.interval:type_name -> Interval
	1,  // 8: EventsResponse.events:type_name -> Event
	9,  // 9: UpdateEventsRequest.updated:type_name -> UpdateEventsRequest.UpdatedEvent
	10, // 10: UpdateEventsRequest.UpdatedEvent.tags:type_name -> UpdateEventsRequest.UpdatedEvent.Tags
	0,  // 11: UpdateEventsRequest.UpdatedEvent.interval:type_name -> Interval
	11, // 12: UpdateEventsRequest.UpdatedEvent.trigger:type_name -> UpdateEventsRequest.UpdatedEvent.Trigger
	13, // 13: UpdateEventsRequest.UpdatedEvent.Trigger.relative:type_name -> google.protobuf.Duration
	12, // 14: UpdateEventsRequest.UpdatedEvent.Trigger.absolute:type_name -> google.protobuf.Timestamp
	2,  // 15: CalendarService.Calendar:input_type -> CalendarRequest
	4,  // 16: CalendarService.Events:input_type -> EventsRequest
	6,  // 17: CalendarService.UpdateEvents:input_type -> UpdateEventsRequest
	3,  // 18: CalendarService.Calendar:output_type -> CalendarResponse
	5,  // 19: CalendarService.Events:output_type -> EventsResponse
	7,  // 20: CalendarService.UpdateEvents:output_type -> UpdateEventsResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_v1_api_proto_init() }
func file_v1_api_proto_init() {
	if File_v1_api_proto != nil {
		return
	}
	file_v1_api_proto_msgTypes[1].OneofWrappers = []any{
		(*Event_Relative)(nil),
		(*Event_Absolute)(nil),
		(*Event_None)(nil),
	}
	file_v1_api_proto_msgTypes[9].OneofWrappers = []any{}
	file_v1_api_proto_msgTypes[11].OneofWrappers = []any{
		(*UpdateEventsRequest_UpdatedEvent_Trigger_Relative)(nil),
		(*UpdateEventsRequest_UpdatedEvent_Trigger_Absolute)(nil),
		(*UpdateEventsRequest_UpdatedEvent_Trigger_None)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_api_proto_rawDesc), len(file_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_api_proto_goTypes,
		DependencyIndexes: file_v1_api_proto_depIdxs,
		MessageInfos:      file_v1_api_proto_msgTypes,
	}.Build()
	File_v1_api_proto = out.File
	file_v1_api_proto_goTypes = nil
	file_v1_api_proto_depIdxs = nil
}
