// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file v1/api.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EventsRequest, EventsResponse } from "./api_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service CalendarService
 */
export const CalendarService = {
  typeName: "CalendarService",
  methods: {
    /**
     * @generated from rpc CalendarService.Events
     */
    events: {
      name: "Events",
      I: EventsRequest,
      O: EventsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

