// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file v1/api.proto (syntax proto3)
/* eslint-disable */

import { CalendarService } from "./api_pb";

/**
 * @generated from rpc CalendarService.Calendar
 */
export const calendar = CalendarService.method.calendar;

/**
 * @generated from rpc CalendarService.Events
 */
export const events = CalendarService.method.events;

/**
 * @generated from rpc CalendarService.UpdateEvents
 */
export const updateEvents = CalendarService.method.updateEvents;
