// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file v1/api.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Duration, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/api.proto.
 */
export const file_v1_api: GenFile = /*@__PURE__*/
  fileDesc("Cgx2MS9hcGkucHJvdG8iXgoISW50ZXJ2YWwSKQoFc3RhcnQYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEicKA2VuZBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAimgIKBUV2ZW50EgoKAmlkGAEgASgNEgwKBG5hbWUYAiABKA0SEAoIbG9jYXRpb24YAyABKAkSEwoLZGVzY3JpcHRpb24YBCABKAkSDAoEdGFncxgFIAMoDRIbCghpbnRlcnZhbBgGIAEoCzIJLkludGVydmFsEisKCGR1cmF0aW9uGAcgASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uEi0KCHJlbGF0aXZlGAggASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uSAASLgoIYWJzb2x1dGUYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSAASDgoEbm9uZRgKIAEoCEgAQgkKB3RyaWdnZXIiEQoPQ2FsZW5kYXJSZXF1ZXN0Im8KEENhbGVuZGFyUmVzcG9uc2USKQoHc291cmNlcxgBIAMoCzIYLkNhbGVuZGFyUmVzcG9uc2UuU291cmNlGjAKBlNvdXJjZRIXCg9jYWxlbmRhcl9zZXJ2ZXIYASABKAkSDQoFbmFtZXMYAiADKAkiPgoNRXZlbnRzUmVxdWVzdBIbCghpbnRlcnZhbBgBIAEoCzIJLkludGVydmFsEhAKCHRpbWV6b25lGAIgASgJIksKDkV2ZW50c1Jlc3BvbnNlEhMKC2V2ZW50X25hbWVzGAEgAygJEgwKBHRhZ3MYAiADKAkSFgoGZXZlbnRzGAMgAygLMgYuRXZlbnQiJQoTVXBkYXRlRXZlbnRzUmVxdWVzdBIOCgZzY3JpcHQYASABKAkiFgoUVXBkYXRlRXZlbnRzUmVzcG9uc2UyqgEKD0NhbGVuZGFyU2VydmljZRIvCghDYWxlbmRhchIQLkNhbGVuZGFyUmVxdWVzdBoRLkNhbGVuZGFyUmVzcG9uc2USKQoGRXZlbnRzEg4uRXZlbnRzUmVxdWVzdBoPLkV2ZW50c1Jlc3BvbnNlEjsKDFVwZGF0ZUV2ZW50cxIULlVwZGF0ZUV2ZW50c1JlcXVlc3QaFS5VcGRhdGVFdmVudHNSZXNwb25zZWIGcHJvdG8z", [file_google_protobuf_timestamp, file_google_protobuf_duration]);

/**
 * @generated from message Interval
 */
export type Interval = Message<"Interval"> & {
  /**
   * @generated from field: google.protobuf.Timestamp start = 1;
   */
  start?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp end = 2;
   */
  end?: Timestamp;
};

/**
 * Describes the message Interval.
 * Use `create(IntervalSchema)` to create a new message.
 */
export const IntervalSchema: GenMessage<Interval> = /*@__PURE__*/
  messageDesc(file_v1_api, 0);

/**
 * @generated from message Event
 */
export type Event = Message<"Event"> & {
  /**
   * @generated from field: uint32 id = 1;
   */
  id: number;

  /**
   * the name is an index for the lookup table of event names
   *
   * @generated from field: uint32 name = 2;
   */
  name: number;

  /**
   * @generated from field: string location = 3;
   */
  location: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * each element is an index for the lookup table of tag names
   *
   * @generated from field: repeated uint32 tags = 5;
   */
  tags: number[];

  /**
   * @generated from field: Interval interval = 6;
   */
  interval?: Interval;

  /**
   * @generated from field: google.protobuf.Duration duration = 7;
   */
  duration?: Duration;

  /**
   * @generated from oneof Event.trigger
   */
  trigger: {
    /**
     * @generated from field: google.protobuf.Duration relative = 8;
     */
    value: Duration;
    case: "relative";
  } | {
    /**
     * @generated from field: google.protobuf.Timestamp absolute = 9;
     */
    value: Timestamp;
    case: "absolute";
  } | {
    /**
     * @generated from field: bool none = 10;
     */
    value: boolean;
    case: "none";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_v1_api, 1);

/**
 * Calendar
 *
 * @generated from message CalendarRequest
 */
export type CalendarRequest = Message<"CalendarRequest"> & {
};

/**
 * Describes the message CalendarRequest.
 * Use `create(CalendarRequestSchema)` to create a new message.
 */
export const CalendarRequestSchema: GenMessage<CalendarRequest> = /*@__PURE__*/
  messageDesc(file_v1_api, 2);

/**
 * @generated from message CalendarResponse
 */
export type CalendarResponse = Message<"CalendarResponse"> & {
  /**
   * @generated from field: repeated CalendarResponse.Source sources = 1;
   */
  sources: CalendarResponse_Source[];
};

/**
 * Describes the message CalendarResponse.
 * Use `create(CalendarResponseSchema)` to create a new message.
 */
export const CalendarResponseSchema: GenMessage<CalendarResponse> = /*@__PURE__*/
  messageDesc(file_v1_api, 3);

/**
 * @generated from message CalendarResponse.Source
 */
export type CalendarResponse_Source = Message<"CalendarResponse.Source"> & {
  /**
   * @generated from field: string calendar_server = 1;
   */
  calendarServer: string;

  /**
   * @generated from field: repeated string names = 2;
   */
  names: string[];
};

/**
 * Describes the message CalendarResponse.Source.
 * Use `create(CalendarResponse_SourceSchema)` to create a new message.
 */
export const CalendarResponse_SourceSchema: GenMessage<CalendarResponse_Source> = /*@__PURE__*/
  messageDesc(file_v1_api, 3, 0);

/**
 * Events
 *
 * @generated from message EventsRequest
 */
export type EventsRequest = Message<"EventsRequest"> & {
  /**
   * @generated from field: Interval interval = 1;
   */
  interval?: Interval;

  /**
   * @generated from field: string timezone = 2;
   */
  timezone: string;
};

/**
 * Describes the message EventsRequest.
 * Use `create(EventsRequestSchema)` to create a new message.
 */
export const EventsRequestSchema: GenMessage<EventsRequest> = /*@__PURE__*/
  messageDesc(file_v1_api, 4);

/**
 * @generated from message EventsResponse
 */
export type EventsResponse = Message<"EventsResponse"> & {
  /**
   * @generated from field: repeated string event_names = 1;
   */
  eventNames: string[];

  /**
   * @generated from field: repeated string tags = 2;
   */
  tags: string[];

  /**
   * @generated from field: repeated Event events = 3;
   */
  events: Event[];
};

/**
 * Describes the message EventsResponse.
 * Use `create(EventsResponseSchema)` to create a new message.
 */
export const EventsResponseSchema: GenMessage<EventsResponse> = /*@__PURE__*/
  messageDesc(file_v1_api, 5);

/**
 * UpdateEvents
 *
 * @generated from message UpdateEventsRequest
 */
export type UpdateEventsRequest = Message<"UpdateEventsRequest"> & {
  /**
   * @generated from field: string script = 1;
   */
  script: string;
};

/**
 * Describes the message UpdateEventsRequest.
 * Use `create(UpdateEventsRequestSchema)` to create a new message.
 */
export const UpdateEventsRequestSchema: GenMessage<UpdateEventsRequest> = /*@__PURE__*/
  messageDesc(file_v1_api, 6);

/**
 * @generated from message UpdateEventsResponse
 */
export type UpdateEventsResponse = Message<"UpdateEventsResponse"> & {
};

/**
 * Describes the message UpdateEventsResponse.
 * Use `create(UpdateEventsResponseSchema)` to create a new message.
 */
export const UpdateEventsResponseSchema: GenMessage<UpdateEventsResponse> = /*@__PURE__*/
  messageDesc(file_v1_api, 7);

/**
 * @generated from service CalendarService
 */
export const CalendarService: GenService<{
  /**
   * @generated from rpc CalendarService.Calendar
   */
  calendar: {
    methodKind: "unary";
    input: typeof CalendarRequestSchema;
    output: typeof CalendarResponseSchema;
  },
  /**
   * @generated from rpc CalendarService.Events
   */
  events: {
    methodKind: "unary";
    input: typeof EventsRequestSchema;
    output: typeof EventsResponseSchema;
  },
  /**
   * @generated from rpc CalendarService.UpdateEvents
   */
  updateEvents: {
    methodKind: "unary";
    input: typeof UpdateEventsRequestSchema;
    output: typeof UpdateEventsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_api, 0);

